# Generated by Django 5.0.4 on 2024-05-13 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Modules',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='project.module'),
            preserve_default=False,
        ),
    ]
