# Generated by Django 5.0.4 on 2024-05-13 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_teacher_modules_teacher_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Module',
            new_name='module',
        ),
    ]
