# Generated by Django 5.0.4 on 2024-05-14 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_module_teacher_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='Class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='project.classes'),
            preserve_default=False,
        ),
    ]
