# Generated by Django 5.0.4 on 2024-05-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_courses_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='Modules',
            field=models.ManyToManyField(to='project.module'),
        ),
    ]
