# Generated by Django 5.0.4 on 2024-05-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_classes_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='niveau',
            field=models.CharField(max_length=50),
        ),
    ]
