# Generated by Django 5.0.4 on 2024-06-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_classes_niveau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='pic',
        ),
        migrations.AddField(
            model_name='courses',
            name='type',
            field=models.CharField(default='txt', max_length=50),
            preserve_default=False,
        ),
    ]
