# Generated by Django 5.0.4 on 2024-06-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_courses_pic_courses_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='file',
            field=models.TextField(max_length=50),
        ),
    ]
