# Generated by Django 5.0.4 on 2024-06-01 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_events_is_voting_event_events_no_voters_events_title_and_more'),
        ('project', '0008_alter_courses_file'),
    ]

    operations = [
    ]
