# Generated by Django 5.0.4 on 2024-06-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_merge_20240601_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
