# Generated by Django 5.0.4 on 2024-06-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_courses_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Notifications',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='Notifications',
            field=models.ManyToManyField(to='project.notifications'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Notifications',
            field=models.ManyToManyField(to='project.notifications'),
        ),
    ]
