# Generated by Django 5.0.4 on 2024-06-02 00:21

from django.db import migrations

def create_trigger(apps, schema_editor):


    with schema_editor.connection.cursor() as cursor:

        cursor.execute("""
            CREATE TRIGGER after_course_insert_single_row
            AFTER INSERT ON Courses
            BEGIN
                INSERT INTO Notifications (Description, Date, Type)
                VALUES (NEW.description , NEW.created , 'course');
            END;
             """)

#WHERE classe_id = NEW.Class_id;
        cursor.execute("""
    CREATE TRIGGER after_multi_course_insert
    AFTER INSERT ON Courses
    BEGIN
        INSERT INTO Student_Notifications (notifications_id, student_id, seen)
        SELECT 1 , student_id, 0
        FROM Student
        
    END;
""")

#(SELECT last_insert_rowid())

def drop_trigger(apps, schema_editor):
    schema_editor.execute("DROP TRIGGER IF EXISTS after_course_insert_single_row;")
    schema_editor.execute("DROP TRIGGER IF EXISTS after_multi_course_insert;")

class Migration(migrations.Migration):
    dependencies = [
        ('project', '0011_notifications_student_notifications_and_more'),  # Update with the correct app name and previous migration file
    ]

    operations = [
        migrations.RunPython(create_trigger, reverse_code=drop_trigger),
    ]