# Generated by Django 5.0.4 on 2024-06-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20240602_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='niveau',
            field=models.CharField(choices=[('P', 'Primaire'), ('M', 'CEM'), ('S', 'Lycée')], max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='file',
            field=models.TextField(max_length=1000),
        ),
    ]
